<OneUIHeader>:
    header_key_field: header_key_field
    header_value_field: header_value_field
    cols: 3
    md_bg_color: [0.7, 0.4, 0.5, 1]
    OneUITextField:
        id: header_key_field
        hint_text: "Key"
    OneUITextField:
        id: header_value_field
        hint_text: "Value"
    MDIconButton:
        icon: "trash-can"
        size_hint_x: None
        width: 80
        on_release: root.trash()

<OneUIHeaders>:
    spacing: 10
    MDBoxLayout:
